# Generated by Django 3.2.19 on 2023-06-26 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Videofile', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('video_key', models.CharField(blank=True, max_length=12, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.TextField(blank=True, choices=[('music', 'Music'), ('movie', 'Movie'), ('drama', 'Drama')], null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes_user', models.ManyToManyField(blank=True, null=True, related_name='likes_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
