# Generated by Django 3.2.19 on 2023-06-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Videofile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='71b655c0-19e5-4273-a000-fa4bfe0d9cf4'),
        ),
    ]
